#!/bin/bash

echo "Enter a sentence: "
read sentence

count=0

for ((i=0; i<${#sentence}; i++))
do
    if [ "${sentence:$i:1}" = " " ]
    then
        count=$((count + 1))
    fi
done

echo "Number of blanks in the sentence: $count"
