#!/bin/bash

# Read words from file
echo File Name :
read FILE
words=$(cat $FILE)

# Loop through words
for word in $words
do
    # Get first and last character of word
    first=${word:0:1}
    last=${word: -1}

    # Check if first and last character are same
    if [[ $first == $last ]]; then
        echo $word
    fi
done


	
